"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_router_dom_1 = require("react-router-dom");
var Header = function () {
    return (React.createElement("header", { className: "main-header" },
        React.createElement(react_router_dom_1.Link, { to: "/dashboard", className: "logo" },
            React.createElement("span", { className: "logo-mini" },
                React.createElement("b", null, "A"),
                "LT"),
            React.createElement("span", { className: "logo-lg" },
                React.createElement("b", null, "Admin"),
                "LTE")),
        React.createElement("nav", { className: "navbar navbar-static-top" },
            React.createElement("a", { href: "fake_url", className: "sidebar-toggle", "data-toggle": "push-menu", role: "button" },
                React.createElement("span", { className: "sr-only" }, "Toggle navigation")),
            React.createElement("div", { className: "navbar-custom-menu" },
                React.createElement("ul", { className: "nav navbar-nav" },
                    React.createElement("li", { className: "dropdown messages-menu" },
                        React.createElement("a", { href: "fake_url", className: "dropdown-toggle", "data-toggle": "dropdown" },
                            React.createElement("i", { className: "fa fa-envelope-o" }),
                            React.createElement("span", { className: "label label-success" }, "4")),
                        React.createElement("ul", { className: "dropdown-menu" },
                            React.createElement("li", { className: "header" }, "You have 4 messages"),
                            React.createElement("li", null,
                                React.createElement("ul", { className: "menu" },
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("div", { className: "pull-left" },
                                                React.createElement("img", { src: "assets/dist/img/user2-160x160.jpg", className: "img-circle", alt: "User Image" })),
                                            React.createElement("h4", null,
                                                "Support Team",
                                                React.createElement("small", null,
                                                    React.createElement("i", { className: "fa fa-clock-o" }),
                                                    " 5 mins")),
                                            React.createElement("p", null, "Why not buy a new awesome theme?"))),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("div", { className: "pull-left" },
                                                React.createElement("img", { src: "assets/dist/img/user3-128x128.jpg", className: "img-circle", alt: "User Image" })),
                                            React.createElement("h4", null,
                                                "AdminLTE Design Team",
                                                React.createElement("small", null,
                                                    React.createElement("i", { className: "fa fa-clock-o" }),
                                                    " 2 hours")),
                                            React.createElement("p", null, "Why not buy a new awesome theme?"))),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("div", { className: "pull-left" },
                                                React.createElement("img", { src: "assets/dist/img/user4-128x128.jpg", className: "img-circle", alt: "User Image" })),
                                            React.createElement("h4", null,
                                                "Developers",
                                                React.createElement("small", null,
                                                    React.createElement("i", { className: "fa fa-clock-o" }),
                                                    " Today")),
                                            React.createElement("p", null, "Why not buy a new awesome theme?"))),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("div", { className: "pull-left" },
                                                React.createElement("img", { src: "assets/dist/img/user3-128x128.jpg", className: "img-circle", alt: "User Image" })),
                                            React.createElement("h4", null,
                                                "Sales Department",
                                                React.createElement("small", null,
                                                    React.createElement("i", { className: "fa fa-clock-o" }),
                                                    " Yesterday")),
                                            React.createElement("p", null, "Why not buy a new awesome theme?"))),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("div", { className: "pull-left" },
                                                React.createElement("img", { src: "assets/dist/img/user4-128x128.jpg", className: "img-circle", alt: "User Image" })),
                                            React.createElement("h4", null,
                                                "Reviewers",
                                                React.createElement("small", null,
                                                    React.createElement("i", { className: "fa fa-clock-o" }),
                                                    " 2 days")),
                                            React.createElement("p", null, "Why not buy a new awesome theme?"))))),
                            React.createElement("li", { className: "footer" },
                                React.createElement("a", { href: "fake_url" }, "See All Messages")))),
                    React.createElement("li", { className: "dropdown notifications-menu" },
                        React.createElement("a", { href: "fake_url", className: "dropdown-toggle", "data-toggle": "dropdown" },
                            React.createElement("i", { className: "fa fa-bell-o" }),
                            React.createElement("span", { className: "label label-warning" }, "10")),
                        React.createElement("ul", { className: "dropdown-menu" },
                            React.createElement("li", { className: "header" }, "You have 10 notifications"),
                            React.createElement("li", null,
                                React.createElement("ul", { className: "menu" },
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("i", { className: "fa fa-users text-aqua" }),
                                            " 5 new members joined today")),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("i", { className: "fa fa-warning text-yellow" }),
                                            " Very long description here that may not fit into the page and may cause design problems")),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("i", { className: "fa fa-users text-red" }),
                                            " 5 new members joined")),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("i", { className: "fa fa-shopping-cart text-green" }),
                                            " 25 sales made")),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("i", { className: "fa fa-user text-red" }),
                                            " You changed your username")))),
                            React.createElement("li", { className: "footer" },
                                React.createElement("a", { href: "fake_url" }, "View all")))),
                    React.createElement("li", { className: "dropdown tasks-menu" },
                        React.createElement("a", { href: "fake_url", className: "dropdown-toggle", "data-toggle": "dropdown" },
                            React.createElement("i", { className: "fa fa-flag-o" }),
                            React.createElement("span", { className: "label label-danger" }, "9")),
                        React.createElement("ul", { className: "dropdown-menu" },
                            React.createElement("li", { className: "header" }, "You have 9 tasks"),
                            React.createElement("li", null,
                                React.createElement("ul", { className: "menu" },
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("h3", null,
                                                "Design some buttons",
                                                React.createElement("small", { className: "pull-right" }, "20%")),
                                            React.createElement("div", { className: "progress xs" },
                                                React.createElement("div", { className: "progress-bar progress-bar-aqua", style: { width: '20%' }, role: "progressbar", "aria-valuenow": 20, "aria-valuemin": 0, "aria-valuemax": 100 },
                                                    React.createElement("span", { className: "sr-only" }, "20% Complete"))))),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("h3", null,
                                                "Create a nice theme",
                                                React.createElement("small", { className: "pull-right" }, "40%")),
                                            React.createElement("div", { className: "progress xs" },
                                                React.createElement("div", { className: "progress-bar progress-bar-green", style: { width: '40%' }, role: "progressbar", "aria-valuenow": 20, "aria-valuemin": 0, "aria-valuemax": 100 },
                                                    React.createElement("span", { className: "sr-only" }, "40% Complete"))))),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("h3", null,
                                                "Some task I need to do",
                                                React.createElement("small", { className: "pull-right" }, "60%")),
                                            React.createElement("div", { className: "progress xs" },
                                                React.createElement("div", { className: "progress-bar progress-bar-red", style: { width: '60%' }, role: "progressbar", "aria-valuenow": 20, "aria-valuemin": 0, "aria-valuemax": 100 },
                                                    React.createElement("span", { className: "sr-only" }, "60% Complete"))))),
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "fake_url" },
                                            React.createElement("h3", null,
                                                "Make beautiful transitions",
                                                React.createElement("small", { className: "pull-right" }, "80%")),
                                            React.createElement("div", { className: "progress xs" },
                                                React.createElement("div", { className: "progress-bar progress-bar-yellow", style: { width: '80%' }, role: "progressbar", "aria-valuenow": 20, "aria-valuemin": 0, "aria-valuemax": 100 },
                                                    React.createElement("span", { className: "sr-only" }, "80% Complete"))))))),
                            React.createElement("li", { className: "footer" },
                                React.createElement("a", { href: "fake_url" }, "View all tasks")))),
                    React.createElement("li", { className: "dropdown user user-menu" },
                        React.createElement("a", { href: "fake_url", className: "dropdown-toggle", "data-toggle": "dropdown" },
                            React.createElement("img", { src: "assets/dist/img/user2-160x160.jpg", className: "user-image", alt: "User Image" }),
                            React.createElement("span", { className: "hidden-xs" }, "Alexander Pierce")),
                        React.createElement("ul", { className: "dropdown-menu" },
                            React.createElement("li", { className: "user-header" },
                                React.createElement("img", { src: "assets/dist/img/user2-160x160.jpg", className: "img-circle", alt: "User Image" }),
                                React.createElement("p", null,
                                    "Alexander Pierce - Web Developer",
                                    React.createElement("small", null, "Member since Nov. 2012"))),
                            React.createElement("li", { className: "user-body" },
                                React.createElement("div", { className: "row" },
                                    React.createElement("div", { className: "col-xs-4 text-center" },
                                        React.createElement("a", { href: "fake_url" }, "Followers")),
                                    React.createElement("div", { className: "col-xs-4 text-center" },
                                        React.createElement("a", { href: "fake_url" }, "Sales")),
                                    React.createElement("div", { className: "col-xs-4 text-center" },
                                        React.createElement("a", { href: "fake_url" }, "Friends")))),
                            React.createElement("li", { className: "user-footer" },
                                React.createElement("div", { className: "pull-left" },
                                    React.createElement("a", { href: "fake_url", className: "btn btn-default btn-flat" }, "Profile")),
                                React.createElement("div", { className: "pull-right" },
                                    React.createElement("a", { href: "fake_url", className: "btn btn-default btn-flat" }, "Sign out"))))),
                    React.createElement("li", null,
                        React.createElement("a", { href: "fake_url", "data-toggle": "control-sidebar" },
                            React.createElement("i", { className: "fa fa-gears" }))))))));
};
exports.default = Header;
//# sourceMappingURL=Header.js.map