"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var react_router_dom_1 = require("react-router-dom");
var Sidebar = function () {
    return (React.createElement("aside", { className: "main-sidebar" },
        React.createElement("section", { className: "sidebar" },
            React.createElement("div", { className: "user-panel" },
                React.createElement("div", { className: "pull-left image" },
                    React.createElement("img", { src: "assets/dist/img/user2-160x160.jpg", className: "img-circle", alt: "User Image" })),
                React.createElement("div", { className: "pull-left info" },
                    React.createElement("p", null, "Alexander Pierce"),
                    React.createElement("a", { href: "fake_url" },
                        React.createElement("i", { className: "fa fa-circle text-success" }),
                        " Online"))),
            React.createElement("form", { action: "#", method: "get", className: "sidebar-form" },
                React.createElement("div", { className: "input-group" },
                    React.createElement("input", { type: "text", name: "q", className: "form-control", placeholder: "Search..." }),
                    React.createElement("span", { className: "input-group-btn" },
                        React.createElement("button", { type: "submit", name: "search", id: "search-btn", className: "btn btn-flat" },
                            React.createElement("i", { className: "fa fa-search" }))))),
            React.createElement("ul", { className: "sidebar-menu", "data-widget": "tree" },
                React.createElement("li", { className: "header" }, "MAIN NAVIGATION"),
                React.createElement("li", { className: "active treeview" },
                    React.createElement("a", { href: "fake_url" },
                        React.createElement("i", { className: "fa fa-dashboard" }),
                        " ",
                        React.createElement("span", null, "Dashboard"),
                        React.createElement("span", { className: "pull-right-container" },
                            React.createElement("i", { className: "fa fa-angle-left pull-right" }))),
                    React.createElement("ul", { className: "treeview-menu" },
                        React.createElement("li", { className: "active" },
                            React.createElement(react_router_dom_1.Link, { to: "/dashboard" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Dashboard v1")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "index2.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Dashboard v2")))),
                React.createElement("li", { className: "treeview" },
                    React.createElement("a", { href: "fake_url" },
                        React.createElement("i", { className: "fa fa-files-o" }),
                        React.createElement("span", null, "Layout Options"),
                        React.createElement("span", { className: "pull-right-container" },
                            React.createElement("span", { className: "label label-primary pull-right" }, "4"))),
                    React.createElement("ul", { className: "treeview-menu" },
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/layout/top-nav.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Top Navigation")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/layout/boxed.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Boxed")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/layout/fixed.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Fixed")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/layout/collapsed-sidebar.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Collapsed Sidebar")))),
                React.createElement("li", null,
                    React.createElement(react_router_dom_1.Link, { to: "/widgets" },
                        React.createElement("i", { className: "fa fa-th" }),
                        " ",
                        React.createElement("span", null, "Widgets"),
                        React.createElement("span", { className: "pull-right-container" },
                            React.createElement("small", { className: "label pull-right bg-green" }, "new")))),
                React.createElement("li", { className: "treeview" },
                    React.createElement("a", { href: "fake_url" },
                        React.createElement("i", { className: "fa fa-pie-chart" }),
                        React.createElement("span", null, "Charts"),
                        React.createElement("span", { className: "pull-right-container" },
                            React.createElement("i", { className: "fa fa-angle-left pull-right" }))),
                    React.createElement("ul", { className: "treeview-menu" },
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/charts/chartjs.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " ChartJS")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/charts/morris.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Morris")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/charts/flot.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Flot")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/charts/inline.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Inline charts")))),
                React.createElement("li", { className: "treeview" },
                    React.createElement("a", { href: "fake_url" },
                        React.createElement("i", { className: "fa fa-laptop" }),
                        React.createElement("span", null, "UI Elements"),
                        React.createElement("span", { className: "pull-right-container" },
                            React.createElement("i", { className: "fa fa-angle-left pull-right" }))),
                    React.createElement("ul", { className: "treeview-menu" },
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/UI/general.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " General")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/UI/icons.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Icons")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/UI/buttons.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Buttons")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/UI/sliders.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Sliders")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/UI/timeline.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Timeline")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/UI/modals.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Modals")))),
                React.createElement("li", { className: "treeview" },
                    React.createElement("a", { href: "fake_url" },
                        React.createElement("i", { className: "fa fa-edit" }),
                        " ",
                        React.createElement("span", null, "Forms"),
                        React.createElement("span", { className: "pull-right-container" },
                            React.createElement("i", { className: "fa fa-angle-left pull-right" }))),
                    React.createElement("ul", { className: "treeview-menu" },
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/forms/general.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " General Elements")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/forms/advanced.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Advanced Elements")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/forms/editors.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Editors")))),
                React.createElement("li", { className: "treeview" },
                    React.createElement("a", { href: "fake_url" },
                        React.createElement("i", { className: "fa fa-table" }),
                        " ",
                        React.createElement("span", null, "Tables"),
                        React.createElement("span", { className: "pull-right-container" },
                            React.createElement("i", { className: "fa fa-angle-left pull-right" }))),
                    React.createElement("ul", { className: "treeview-menu" },
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/tables/simple.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Simple tables")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/tables/data.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Data tables")))),
                React.createElement("li", null,
                    React.createElement("a", { href: "pages/calendar.html" },
                        React.createElement("i", { className: "fa fa-calendar" }),
                        " ",
                        React.createElement("span", null, "Calendar"),
                        React.createElement("span", { className: "pull-right-container" },
                            React.createElement("small", { className: "label pull-right bg-red" }, "3"),
                            React.createElement("small", { className: "label pull-right bg-blue" }, "17")))),
                React.createElement("li", null,
                    React.createElement("a", { href: "pages/mailbox/mailbox.html" },
                        React.createElement("i", { className: "fa fa-envelope" }),
                        " ",
                        React.createElement("span", null, "Mailbox"),
                        React.createElement("span", { className: "pull-right-container" },
                            React.createElement("small", { className: "label pull-right bg-yellow" }, "12"),
                            React.createElement("small", { className: "label pull-right bg-green" }, "16"),
                            React.createElement("small", { className: "label pull-right bg-red" }, "5")))),
                React.createElement("li", { className: "treeview" },
                    React.createElement("a", { href: "fake_url" },
                        React.createElement("i", { className: "fa fa-folder" }),
                        " ",
                        React.createElement("span", null, "Examples"),
                        React.createElement("span", { className: "pull-right-container" },
                            React.createElement("i", { className: "fa fa-angle-left pull-right" }))),
                    React.createElement("ul", { className: "treeview-menu" },
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/examples/invoice.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Invoice")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/examples/profile.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Profile")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/examples/login.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Login")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/examples/register.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Register")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/examples/lockscreen.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Lockscreen")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/examples/404.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " 404 Error")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/examples/500.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " 500 Error")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/examples/blank.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Blank Page")),
                        React.createElement("li", null,
                            React.createElement("a", { href: "pages/examples/pace.html" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Pace Page")))),
                React.createElement("li", { className: "treeview" },
                    React.createElement("a", { href: "fake_url" },
                        React.createElement("i", { className: "fa fa-share" }),
                        " ",
                        React.createElement("span", null, "Multilevel"),
                        React.createElement("span", { className: "pull-right-container" },
                            React.createElement("i", { className: "fa fa-angle-left pull-right" }))),
                    React.createElement("ul", { className: "treeview-menu" },
                        React.createElement("li", null,
                            React.createElement("a", { href: "fake_url" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Level One")),
                        React.createElement("li", { className: "treeview" },
                            React.createElement("a", { href: "fake_url" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Level One",
                                React.createElement("span", { className: "pull-right-container" },
                                    React.createElement("i", { className: "fa fa-angle-left pull-right" }))),
                            React.createElement("ul", { className: "treeview-menu" },
                                React.createElement("li", null,
                                    React.createElement("a", { href: "fake_url" },
                                        React.createElement("i", { className: "fa fa-circle-o" }),
                                        " Level Two")),
                                React.createElement("li", { className: "treeview" },
                                    React.createElement("a", { href: "fake_url" },
                                        React.createElement("i", { className: "fa fa-circle-o" }),
                                        " Level Two",
                                        React.createElement("span", { className: "pull-right-container" },
                                            React.createElement("i", { className: "fa fa-angle-left pull-right" }))),
                                    React.createElement("ul", { className: "treeview-menu" },
                                        React.createElement("li", null,
                                            React.createElement("a", { href: "fake_url" },
                                                React.createElement("i", { className: "fa fa-circle-o" }),
                                                " Level Three")),
                                        React.createElement("li", null,
                                            React.createElement("a", { href: "fake_url" },
                                                React.createElement("i", { className: "fa fa-circle-o" }),
                                                " Level Three")))))),
                        React.createElement("li", null,
                            React.createElement("a", { href: "fake_url" },
                                React.createElement("i", { className: "fa fa-circle-o" }),
                                " Level One")))),
                React.createElement("li", null,
                    React.createElement("a", { href: "https://adminlte.io/docs" },
                        React.createElement("i", { className: "fa fa-book" }),
                        " ",
                        React.createElement("span", null, "Documentation"))),
                React.createElement("li", { className: "header" }, "LABELS"),
                React.createElement("li", null,
                    React.createElement("a", { href: "fake_url" },
                        React.createElement("i", { className: "fa fa-circle-o text-red" }),
                        " ",
                        React.createElement("span", null, "Important"))),
                React.createElement("li", null,
                    React.createElement("a", { href: "fake_url" },
                        React.createElement("i", { className: "fa fa-circle-o text-yellow" }),
                        " ",
                        React.createElement("span", null, "Warning"))),
                React.createElement("li", null,
                    React.createElement("a", { href: "fake_url" },
                        React.createElement("i", { className: "fa fa-circle-o text-aqua" }),
                        " ",
                        React.createElement("span", null, "Information")))))));
};
exports.default = Sidebar;
//# sourceMappingURL=Sidebar.js.map