"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var React = require("react");
var Widgets = function () {
    return (React.createElement("div", { className: "content-wrapper" },
        React.createElement("section", { className: "content-header" },
            React.createElement("h1", null,
                "Widgets",
                React.createElement("small", null, "Preview page")),
            React.createElement("ol", { className: "breadcrumb" },
                React.createElement("li", null,
                    React.createElement("a", { href: "#" },
                        React.createElement("i", { className: "fa fa-dashboard" }),
                        " Home")),
                React.createElement("li", { className: "active" }, "Widgets"))),
        React.createElement("section", { className: "content" },
            React.createElement("div", { className: "row" },
                React.createElement("div", { className: "col-md-3 col-sm-6 col-xs-12" },
                    React.createElement("div", { className: "info-box" },
                        React.createElement("span", { className: "info-box-icon bg-aqua" },
                            React.createElement("i", { className: "fa fa-envelope-o" })),
                        React.createElement("div", { className: "info-box-content" },
                            React.createElement("span", { className: "info-box-text" }, "Messages"),
                            React.createElement("span", { className: "info-box-number" }, "1,410")))),
                React.createElement("div", { className: "col-md-3 col-sm-6 col-xs-12" },
                    React.createElement("div", { className: "info-box" },
                        React.createElement("span", { className: "info-box-icon bg-green" },
                            React.createElement("i", { className: "fa fa-flag-o" })),
                        React.createElement("div", { className: "info-box-content" },
                            React.createElement("span", { className: "info-box-text" }, "Bookmarks"),
                            React.createElement("span", { className: "info-box-number" }, "410")))),
                React.createElement("div", { className: "col-md-3 col-sm-6 col-xs-12" },
                    React.createElement("div", { className: "info-box" },
                        React.createElement("span", { className: "info-box-icon bg-yellow" },
                            React.createElement("i", { className: "fa fa-files-o" })),
                        React.createElement("div", { className: "info-box-content" },
                            React.createElement("span", { className: "info-box-text" }, "Uploads"),
                            React.createElement("span", { className: "info-box-number" }, "13,648")))),
                React.createElement("div", { className: "col-md-3 col-sm-6 col-xs-12" },
                    React.createElement("div", { className: "info-box" },
                        React.createElement("span", { className: "info-box-icon bg-red" },
                            React.createElement("i", { className: "fa fa-star-o" })),
                        React.createElement("div", { className: "info-box-content" },
                            React.createElement("span", { className: "info-box-text" }, "Likes"),
                            React.createElement("span", { className: "info-box-number" }, "93,139"))))),
            React.createElement("div", { className: "row" },
                React.createElement("div", { className: "col-md-3 col-sm-6 col-xs-12" },
                    React.createElement("div", { className: "info-box bg-aqua" },
                        React.createElement("span", { className: "info-box-icon" },
                            React.createElement("i", { className: "fa fa-bookmark-o" })),
                        React.createElement("div", { className: "info-box-content" },
                            React.createElement("span", { className: "info-box-text" }, "Bookmarks"),
                            React.createElement("span", { className: "info-box-number" }, "41,410"),
                            React.createElement("div", { className: "progress" },
                                React.createElement("div", { className: "progress-bar", style: { width: '70%' } })),
                            React.createElement("span", { className: "progress-description" }, "70% Increase in 30 Days")))),
                React.createElement("div", { className: "col-md-3 col-sm-6 col-xs-12" },
                    React.createElement("div", { className: "info-box bg-green" },
                        React.createElement("span", { className: "info-box-icon" },
                            React.createElement("i", { className: "fa fa-thumbs-o-up" })),
                        React.createElement("div", { className: "info-box-content" },
                            React.createElement("span", { className: "info-box-text" }, "Likes"),
                            React.createElement("span", { className: "info-box-number" }, "41,410"),
                            React.createElement("div", { className: "progress" },
                                React.createElement("div", { className: "progress-bar", style: { width: '70%' } })),
                            React.createElement("span", { className: "progress-description" }, "70% Increase in 30 Days")))),
                React.createElement("div", { className: "col-md-3 col-sm-6 col-xs-12" },
                    React.createElement("div", { className: "info-box bg-yellow" },
                        React.createElement("span", { className: "info-box-icon" },
                            React.createElement("i", { className: "fa fa-calendar" })),
                        React.createElement("div", { className: "info-box-content" },
                            React.createElement("span", { className: "info-box-text" }, "Events"),
                            React.createElement("span", { className: "info-box-number" }, "41,410"),
                            React.createElement("div", { className: "progress" },
                                React.createElement("div", { className: "progress-bar", style: { width: '70%' } })),
                            React.createElement("span", { className: "progress-description" }, "70% Increase in 30 Days")))),
                React.createElement("div", { className: "col-md-3 col-sm-6 col-xs-12" },
                    React.createElement("div", { className: "info-box bg-red" },
                        React.createElement("span", { className: "info-box-icon" },
                            React.createElement("i", { className: "fa fa-comments-o" })),
                        React.createElement("div", { className: "info-box-content" },
                            React.createElement("span", { className: "info-box-text" }, "Comments"),
                            React.createElement("span", { className: "info-box-number" }, "41,410"),
                            React.createElement("div", { className: "progress" },
                                React.createElement("div", { className: "progress-bar", style: { width: '70%' } })),
                            React.createElement("span", { className: "progress-description" }, "70% Increase in 30 Days"))))),
            React.createElement("div", { className: "row" },
                React.createElement("div", { className: "col-lg-3 col-xs-6" },
                    React.createElement("div", { className: "small-box bg-aqua" },
                        React.createElement("div", { className: "inner" },
                            React.createElement("h3", null, "150"),
                            React.createElement("p", null, "New Orders")),
                        React.createElement("div", { className: "icon" },
                            React.createElement("i", { className: "fa fa-shopping-cart" })),
                        React.createElement("a", { href: "#", className: "small-box-footer" },
                            "More info ",
                            React.createElement("i", { className: "fa fa-arrow-circle-right" })))),
                React.createElement("div", { className: "col-lg-3 col-xs-6" },
                    React.createElement("div", { className: "small-box bg-green" },
                        React.createElement("div", { className: "inner" },
                            React.createElement("h3", null,
                                "53",
                                React.createElement("sup", { style: { fontSize: 20 } }, "%")),
                            React.createElement("p", null, "Bounce Rate")),
                        React.createElement("div", { className: "icon" },
                            React.createElement("i", { className: "ion ion-stats-bars" })),
                        React.createElement("a", { href: "#", className: "small-box-footer" },
                            "More info ",
                            React.createElement("i", { className: "fa fa-arrow-circle-right" })))),
                React.createElement("div", { className: "col-lg-3 col-xs-6" },
                    React.createElement("div", { className: "small-box bg-yellow" },
                        React.createElement("div", { className: "inner" },
                            React.createElement("h3", null, "44"),
                            React.createElement("p", null, "User Registrations")),
                        React.createElement("div", { className: "icon" },
                            React.createElement("i", { className: "ion ion-person-add" })),
                        React.createElement("a", { href: "#", className: "small-box-footer" },
                            "More info ",
                            React.createElement("i", { className: "fa fa-arrow-circle-right" })))),
                React.createElement("div", { className: "col-lg-3 col-xs-6" },
                    React.createElement("div", { className: "small-box bg-red" },
                        React.createElement("div", { className: "inner" },
                            React.createElement("h3", null, "65"),
                            React.createElement("p", null, "Unique Visitors")),
                        React.createElement("div", { className: "icon" },
                            React.createElement("i", { className: "ion ion-pie-graph" })),
                        React.createElement("a", { href: "#", className: "small-box-footer" },
                            "More info ",
                            React.createElement("i", { className: "fa fa-arrow-circle-right" }))))),
            React.createElement("div", { className: "row" },
                React.createElement("div", { className: "col-md-3" },
                    React.createElement("div", { className: "box box-default collapsed-box" },
                        React.createElement("div", { className: "box-header with-border" },
                            React.createElement("h3", { className: "box-title" }, "Expandable"),
                            React.createElement("div", { className: "box-tools pull-right" },
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "collapse" },
                                    React.createElement("i", { className: "fa fa-plus" })))),
                        React.createElement("div", { className: "box-body" }, "The body of the box"))),
                React.createElement("div", { className: "col-md-3" },
                    React.createElement("div", { className: "box box-success" },
                        React.createElement("div", { className: "box-header with-border" },
                            React.createElement("h3", { className: "box-title" }, "Removable"),
                            React.createElement("div", { className: "box-tools pull-right" },
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "remove" },
                                    React.createElement("i", { className: "fa fa-times" })))),
                        React.createElement("div", { className: "box-body" }, "The body of the box"))),
                React.createElement("div", { className: "col-md-3" },
                    React.createElement("div", { className: "box box-warning" },
                        React.createElement("div", { className: "box-header with-border" },
                            React.createElement("h3", { className: "box-title" }, "Collapsable"),
                            React.createElement("div", { className: "box-tools pull-right" },
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "collapse" },
                                    React.createElement("i", { className: "fa fa-minus" })))),
                        React.createElement("div", { className: "box-body" }, "The body of the box"))),
                React.createElement("div", { className: "col-md-3" },
                    React.createElement("div", { className: "box box-danger" },
                        React.createElement("div", { className: "box-header" },
                            React.createElement("h3", { className: "box-title" }, "Loading state")),
                        React.createElement("div", { className: "box-body" }, "The body of the box"),
                        React.createElement("div", { className: "overlay" },
                            React.createElement("i", { className: "fa fa-refresh fa-spin" }))))),
            React.createElement("div", { className: "row" },
                React.createElement("div", { className: "col-md-3" },
                    React.createElement("div", { className: "box box-default collapsed-box box-solid" },
                        React.createElement("div", { className: "box-header with-border" },
                            React.createElement("h3", { className: "box-title" }, "Expandable"),
                            React.createElement("div", { className: "box-tools pull-right" },
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "collapse" },
                                    React.createElement("i", { className: "fa fa-plus" })))),
                        React.createElement("div", { className: "box-body" }, "The body of the box"))),
                React.createElement("div", { className: "col-md-3" },
                    React.createElement("div", { className: "box box-success box-solid" },
                        React.createElement("div", { className: "box-header with-border" },
                            React.createElement("h3", { className: "box-title" }, "Removable"),
                            React.createElement("div", { className: "box-tools pull-right" },
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "remove" },
                                    React.createElement("i", { className: "fa fa-times" })))),
                        React.createElement("div", { className: "box-body" }, "The body of the box"))),
                React.createElement("div", { className: "col-md-3" },
                    React.createElement("div", { className: "box box-warning box-solid" },
                        React.createElement("div", { className: "box-header with-border" },
                            React.createElement("h3", { className: "box-title" }, "Collapsable"),
                            React.createElement("div", { className: "box-tools pull-right" },
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "collapse" },
                                    React.createElement("i", { className: "fa fa-minus" })))),
                        React.createElement("div", { className: "box-body" }, "The body of the box"))),
                React.createElement("div", { className: "col-md-3" },
                    React.createElement("div", { className: "box box-danger box-solid" },
                        React.createElement("div", { className: "box-header" },
                            React.createElement("h3", { className: "box-title" }, "Loading state")),
                        React.createElement("div", { className: "box-body" }, "The body of the box"),
                        React.createElement("div", { className: "overlay" },
                            React.createElement("i", { className: "fa fa-refresh fa-spin" }))))),
            React.createElement("div", { className: "row" },
                React.createElement("div", { className: "col-md-3" },
                    React.createElement("div", { className: "box box-primary direct-chat direct-chat-primary" },
                        React.createElement("div", { className: "box-header with-border" },
                            React.createElement("h3", { className: "box-title" }, "Direct Chat"),
                            React.createElement("div", { className: "box-tools pull-right" },
                                React.createElement("span", { "data-toggle": "tooltip", title: "3 New Messages", className: "badge bg-light-blue" }, "3"),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "collapse" },
                                    React.createElement("i", { className: "fa fa-minus" })),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-toggle": "tooltip", title: "Contacts", "data-widget": "chat-pane-toggle" },
                                    React.createElement("i", { className: "fa fa-comments" })),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "remove" },
                                    React.createElement("i", { className: "fa fa-times" })))),
                        React.createElement("div", { className: "box-body" },
                            React.createElement("div", { className: "direct-chat-messages" },
                                React.createElement("div", { className: "direct-chat-msg" },
                                    React.createElement("div", { className: "direct-chat-info clearfix" },
                                        React.createElement("span", { className: "direct-chat-name pull-left" }, "Alexander Pierce"),
                                        React.createElement("span", { className: "direct-chat-timestamp pull-right" }, "23 Jan 2:00 pm")),
                                    React.createElement("img", { className: "direct-chat-img", src: "assets/dist/img/user1-128x128.jpg", alt: "Message User Image" }),
                                    React.createElement("div", { className: "direct-chat-text" }, "Is this template really for free? That's unbelievable!")),
                                React.createElement("div", { className: "direct-chat-msg right" },
                                    React.createElement("div", { className: "direct-chat-info clearfix" },
                                        React.createElement("span", { className: "direct-chat-name pull-right" }, "Sarah Bullock"),
                                        React.createElement("span", { className: "direct-chat-timestamp pull-left" }, "23 Jan 2:05 pm")),
                                    React.createElement("img", { className: "direct-chat-img", src: "assets/dist/img/user3-128x128.jpg", alt: "Message User Image" }),
                                    React.createElement("div", { className: "direct-chat-text" }, "You better believe it!"))),
                            React.createElement("div", { className: "direct-chat-contacts" },
                                React.createElement("ul", { className: "contacts-list" },
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "#" },
                                            React.createElement("img", { className: "contacts-list-img", src: "assets/dist/img/user1-128x128.jpg", alt: "User Image" }),
                                            React.createElement("div", { className: "contacts-list-info" },
                                                React.createElement("span", { className: "contacts-list-name" },
                                                    "Count Dracula",
                                                    React.createElement("small", { className: "contacts-list-date pull-right" }, "2/28/2015")),
                                                React.createElement("span", { className: "contacts-list-msg" }, "How have you been? I was..."))))))),
                        React.createElement("div", { className: "box-footer" },
                            React.createElement("form", { action: "#", method: "post" },
                                React.createElement("div", { className: "input-group" },
                                    React.createElement("input", { type: "text", name: "message", placeholder: "Type Message ...", className: "form-control" }),
                                    React.createElement("span", { className: "input-group-btn" },
                                        React.createElement("button", { type: "submit", className: "btn btn-primary btn-flat" }, "Send"))))))),
                React.createElement("div", { className: "col-md-3" },
                    React.createElement("div", { className: "box box-success direct-chat direct-chat-success" },
                        React.createElement("div", { className: "box-header with-border" },
                            React.createElement("h3", { className: "box-title" }, "Direct Chat"),
                            React.createElement("div", { className: "box-tools pull-right" },
                                React.createElement("span", { "data-toggle": "tooltip", title: "3 New Messages", className: "badge bg-green" }, "3"),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "collapse" },
                                    React.createElement("i", { className: "fa fa-minus" })),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-toggle": "tooltip", title: "Contacts", "data-widget": "chat-pane-toggle" },
                                    React.createElement("i", { className: "fa fa-comments" })),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "remove" },
                                    React.createElement("i", { className: "fa fa-times" })))),
                        React.createElement("div", { className: "box-body" },
                            React.createElement("div", { className: "direct-chat-messages" },
                                React.createElement("div", { className: "direct-chat-msg" },
                                    React.createElement("div", { className: "direct-chat-info clearfix" },
                                        React.createElement("span", { className: "direct-chat-name pull-left" }, "Alexander Pierce"),
                                        React.createElement("span", { className: "direct-chat-timestamp pull-right" }, "23 Jan 2:00 pm")),
                                    React.createElement("img", { className: "direct-chat-img", src: "assets/dist/img/user1-128x128.jpg", alt: "Message User Image" }),
                                    React.createElement("div", { className: "direct-chat-text" }, "Is this template really for free? That's unbelievable!")),
                                React.createElement("div", { className: "direct-chat-msg right" },
                                    React.createElement("div", { className: "direct-chat-info clearfix" },
                                        React.createElement("span", { className: "direct-chat-name pull-right" }, "Sarah Bullock"),
                                        React.createElement("span", { className: "direct-chat-timestamp pull-left" }, "23 Jan 2:05 pm")),
                                    React.createElement("img", { className: "direct-chat-img", src: "assets/dist/img/user3-128x128.jpg", alt: "Message User Image" }),
                                    React.createElement("div", { className: "direct-chat-text" }, "You better believe it!"))),
                            React.createElement("div", { className: "direct-chat-contacts" },
                                React.createElement("ul", { className: "contacts-list" },
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "#" },
                                            React.createElement("img", { className: "contacts-list-img", src: "assets/dist/img/user1-128x128.jpg", alt: "User Image" }),
                                            React.createElement("div", { className: "contacts-list-info" },
                                                React.createElement("span", { className: "contacts-list-name" },
                                                    "Count Dracula",
                                                    React.createElement("small", { className: "contacts-list-date pull-right" }, "2/28/2015")),
                                                React.createElement("span", { className: "contacts-list-msg" }, "How have you been? I was..."))))))),
                        React.createElement("div", { className: "box-footer" },
                            React.createElement("form", { action: "#", method: "post" },
                                React.createElement("div", { className: "input-group" },
                                    React.createElement("input", { type: "text", name: "message", placeholder: "Type Message ...", className: "form-control" }),
                                    React.createElement("span", { className: "input-group-btn" },
                                        React.createElement("button", { type: "submit", className: "btn btn-success btn-flat" }, "Send"))))))),
                React.createElement("div", { className: "col-md-3" },
                    React.createElement("div", { className: "box box-warning direct-chat direct-chat-warning" },
                        React.createElement("div", { className: "box-header with-border" },
                            React.createElement("h3", { className: "box-title" }, "Direct Chat"),
                            React.createElement("div", { className: "box-tools pull-right" },
                                React.createElement("span", { "data-toggle": "tooltip", title: "3 New Messages", className: "badge bg-yellow" }, "3"),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "collapse" },
                                    React.createElement("i", { className: "fa fa-minus" })),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-toggle": "tooltip", title: "Contacts", "data-widget": "chat-pane-toggle" },
                                    React.createElement("i", { className: "fa fa-comments" })),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "remove" },
                                    React.createElement("i", { className: "fa fa-times" })))),
                        React.createElement("div", { className: "box-body" },
                            React.createElement("div", { className: "direct-chat-messages" },
                                React.createElement("div", { className: "direct-chat-msg" },
                                    React.createElement("div", { className: "direct-chat-info clearfix" },
                                        React.createElement("span", { className: "direct-chat-name pull-left" }, "Alexander Pierce"),
                                        React.createElement("span", { className: "direct-chat-timestamp pull-right" }, "23 Jan 2:00 pm")),
                                    React.createElement("img", { className: "direct-chat-img", src: "assets/dist/img/user1-128x128.jpg", alt: "Message User Image" }),
                                    React.createElement("div", { className: "direct-chat-text" }, "Is this template really for free? That's unbelievable!")),
                                React.createElement("div", { className: "direct-chat-msg right" },
                                    React.createElement("div", { className: "direct-chat-info clearfix" },
                                        React.createElement("span", { className: "direct-chat-name pull-right" }, "Sarah Bullock"),
                                        React.createElement("span", { className: "direct-chat-timestamp pull-left" }, "23 Jan 2:05 pm")),
                                    React.createElement("img", { className: "direct-chat-img", src: "assets/dist/img/user3-128x128.jpg", alt: "Message User Image" }),
                                    React.createElement("div", { className: "direct-chat-text" }, "You better believe it!"))),
                            React.createElement("div", { className: "direct-chat-contacts" },
                                React.createElement("ul", { className: "contacts-list" },
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "#" },
                                            React.createElement("img", { className: "contacts-list-img", src: "assets/dist/img/user1-128x128.jpg", alt: "User Image" }),
                                            React.createElement("div", { className: "contacts-list-info" },
                                                React.createElement("span", { className: "contacts-list-name" },
                                                    "Count Dracula",
                                                    React.createElement("small", { className: "contacts-list-date pull-right" }, "2/28/2015")),
                                                React.createElement("span", { className: "contacts-list-msg" }, "How have you been? I was..."))))))),
                        React.createElement("div", { className: "box-footer" },
                            React.createElement("form", { action: "#", method: "post" },
                                React.createElement("div", { className: "input-group" },
                                    React.createElement("input", { type: "text", name: "message", placeholder: "Type Message ...", className: "form-control" }),
                                    React.createElement("span", { className: "input-group-btn" },
                                        React.createElement("button", { type: "submit", className: "btn btn-warning btn-flat" }, "Send"))))))),
                React.createElement("div", { className: "col-md-3" },
                    React.createElement("div", { className: "box box-danger direct-chat direct-chat-danger" },
                        React.createElement("div", { className: "box-header with-border" },
                            React.createElement("h3", { className: "box-title" }, "Direct Chat"),
                            React.createElement("div", { className: "box-tools pull-right" },
                                React.createElement("span", { "data-toggle": "tooltip", title: "3 New Messages", className: "badge bg-red" }, "3"),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "collapse" },
                                    React.createElement("i", { className: "fa fa-minus" })),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-toggle": "tooltip", title: "Contacts", "data-widget": "chat-pane-toggle" },
                                    React.createElement("i", { className: "fa fa-comments" })),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "remove" },
                                    React.createElement("i", { className: "fa fa-times" })))),
                        React.createElement("div", { className: "box-body" },
                            React.createElement("div", { className: "direct-chat-messages" },
                                React.createElement("div", { className: "direct-chat-msg" },
                                    React.createElement("div", { className: "direct-chat-info clearfix" },
                                        React.createElement("span", { className: "direct-chat-name pull-left" }, "Alexander Pierce"),
                                        React.createElement("span", { className: "direct-chat-timestamp pull-right" }, "23 Jan 2:00 pm")),
                                    React.createElement("img", { className: "direct-chat-img", src: "assets/dist/img/user1-128x128.jpg", alt: "Message User Image" }),
                                    React.createElement("div", { className: "direct-chat-text" }, "Is this template really for free? That's unbelievable!")),
                                React.createElement("div", { className: "direct-chat-msg right" },
                                    React.createElement("div", { className: "direct-chat-info clearfix" },
                                        React.createElement("span", { className: "direct-chat-name pull-right" }, "Sarah Bullock"),
                                        React.createElement("span", { className: "direct-chat-timestamp pull-left" }, "23 Jan 2:05 pm")),
                                    React.createElement("img", { className: "direct-chat-img", src: "assets/dist/img/user3-128x128.jpg", alt: "Message User Image" }),
                                    React.createElement("div", { className: "direct-chat-text" }, "You better believe it!"))),
                            React.createElement("div", { className: "direct-chat-contacts" },
                                React.createElement("ul", { className: "contacts-list" },
                                    React.createElement("li", null,
                                        React.createElement("a", { href: "#" },
                                            React.createElement("img", { className: "contacts-list-img", src: "assets/dist/img/user1-128x128.jpg", alt: "User Image" }),
                                            React.createElement("div", { className: "contacts-list-info" },
                                                React.createElement("span", { className: "contacts-list-name" },
                                                    "Count Dracula",
                                                    React.createElement("small", { className: "contacts-list-date pull-right" }, "2/28/2015")),
                                                React.createElement("span", { className: "contacts-list-msg" }, "How have you been? I was..."))))))),
                        React.createElement("div", { className: "box-footer" },
                            React.createElement("form", { action: "#", method: "post" },
                                React.createElement("div", { className: "input-group" },
                                    React.createElement("input", { type: "text", name: "message", placeholder: "Type Message ...", className: "form-control" }),
                                    React.createElement("span", { className: "input-group-btn" },
                                        React.createElement("button", { type: "submit", className: "btn btn-danger btn-flat" }, "Send")))))))),
            React.createElement("h2", { className: "page-header" }, "Social Widgets"),
            React.createElement("div", { className: "row" },
                React.createElement("div", { className: "col-md-4" },
                    React.createElement("div", { className: "box box-widget widget-user-2" },
                        React.createElement("div", { className: "widget-user-header bg-yellow" },
                            React.createElement("div", { className: "widget-user-image" },
                                React.createElement("img", { className: "img-circle", src: "assets/dist/img/user7-128x128.jpg", alt: "User Avatar" })),
                            React.createElement("h3", { className: "widget-user-username" }, "Nadia Carmichael"),
                            React.createElement("h5", { className: "widget-user-desc" }, "Lead Developer")),
                        React.createElement("div", { className: "box-footer no-padding" },
                            React.createElement("ul", { className: "nav nav-stacked" },
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" },
                                        "Projects ",
                                        React.createElement("span", { className: "pull-right badge bg-blue" }, "31"))),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" },
                                        "Tasks ",
                                        React.createElement("span", { className: "pull-right badge bg-aqua" }, "5"))),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" },
                                        "Completed Projects ",
                                        React.createElement("span", { className: "pull-right badge bg-green" }, "12"))),
                                React.createElement("li", null,
                                    React.createElement("a", { href: "#" },
                                        "Followers ",
                                        React.createElement("span", { className: "pull-right badge bg-red" }, "842"))))))),
                React.createElement("div", { className: "col-md-4" },
                    React.createElement("div", { className: "box box-widget widget-user" },
                        React.createElement("div", { className: "widget-user-header bg-aqua-active" },
                            React.createElement("h3", { className: "widget-user-username" }, "Alexander Pierce"),
                            React.createElement("h5", { className: "widget-user-desc" }, "Founder & CEO")),
                        React.createElement("div", { className: "widget-user-image" },
                            React.createElement("img", { className: "img-circle", src: "assets/dist/img/user1-128x128.jpg", alt: "User Avatar" })),
                        React.createElement("div", { className: "box-footer" },
                            React.createElement("div", { className: "row" },
                                React.createElement("div", { className: "col-sm-4 border-right" },
                                    React.createElement("div", { className: "description-block" },
                                        React.createElement("h5", { className: "description-header" }, "3,200"),
                                        React.createElement("span", { className: "description-text" }, "SALES"))),
                                React.createElement("div", { className: "col-sm-4 border-right" },
                                    React.createElement("div", { className: "description-block" },
                                        React.createElement("h5", { className: "description-header" }, "13,000"),
                                        React.createElement("span", { className: "description-text" }, "FOLLOWERS"))),
                                React.createElement("div", { className: "col-sm-4" },
                                    React.createElement("div", { className: "description-block" },
                                        React.createElement("h5", { className: "description-header" }, "35"),
                                        React.createElement("span", { className: "description-text" }, "PRODUCTS"))))))),
                React.createElement("div", { className: "col-md-4" },
                    React.createElement("div", { className: "box box-widget widget-user" },
                        React.createElement("div", { className: "widget-user-header bg-black", style: { background: 'url("assets/dist/img/photo1.png") center center' } },
                            React.createElement("h3", { className: "widget-user-username" }, "Elizabeth Pierce"),
                            React.createElement("h5", { className: "widget-user-desc" }, "Web Designer")),
                        React.createElement("div", { className: "widget-user-image" },
                            React.createElement("img", { className: "img-circle", src: "assets/dist/img/user3-128x128.jpg", alt: "User Avatar" })),
                        React.createElement("div", { className: "box-footer" },
                            React.createElement("div", { className: "row" },
                                React.createElement("div", { className: "col-sm-4 border-right" },
                                    React.createElement("div", { className: "description-block" },
                                        React.createElement("h5", { className: "description-header" }, "3,200"),
                                        React.createElement("span", { className: "description-text" }, "SALES"))),
                                React.createElement("div", { className: "col-sm-4 border-right" },
                                    React.createElement("div", { className: "description-block" },
                                        React.createElement("h5", { className: "description-header" }, "13,000"),
                                        React.createElement("span", { className: "description-text" }, "FOLLOWERS"))),
                                React.createElement("div", { className: "col-sm-4" },
                                    React.createElement("div", { className: "description-block" },
                                        React.createElement("h5", { className: "description-header" }, "35"),
                                        React.createElement("span", { className: "description-text" }, "PRODUCTS")))))))),
            React.createElement("div", { className: "row" },
                React.createElement("div", { className: "col-md-6" },
                    React.createElement("div", { className: "box box-widget" },
                        React.createElement("div", { className: "box-header with-border" },
                            React.createElement("div", { className: "user-block" },
                                React.createElement("img", { className: "img-circle", src: "assets/dist/img/user1-128x128.jpg", alt: "User Image" }),
                                React.createElement("span", { className: "username" },
                                    React.createElement("a", { href: "#" }, "Jonathan Burke Jr.")),
                                React.createElement("span", { className: "description" }, "Shared publicly - 7:30 PM Today")),
                            React.createElement("div", { className: "box-tools" },
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-toggle": "tooltip", title: "Mark as read" },
                                    React.createElement("i", { className: "fa fa-circle-o" })),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "collapse" },
                                    React.createElement("i", { className: "fa fa-minus" })),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "remove" },
                                    React.createElement("i", { className: "fa fa-times" })))),
                        React.createElement("div", { className: "box-body" },
                            React.createElement("img", { className: "img-responsive pad", src: "assets/dist/img/photo2.png", alt: "Photo" }),
                            React.createElement("p", null, "I took this photo this morning. What do you guys think?"),
                            React.createElement("button", { type: "button", className: "btn btn-default btn-xs" },
                                React.createElement("i", { className: "fa fa-share" }),
                                " Share"),
                            React.createElement("button", { type: "button", className: "btn btn-default btn-xs" },
                                React.createElement("i", { className: "fa fa-thumbs-o-up" }),
                                " Like"),
                            React.createElement("span", { className: "pull-right text-muted" }, "127 likes - 3 comments")),
                        React.createElement("div", { className: "box-footer box-comments" },
                            React.createElement("div", { className: "box-comment" },
                                React.createElement("img", { className: "img-circle img-sm", src: "assets/dist/img/user3-128x128.jpg", alt: "User Image" }),
                                React.createElement("div", { className: "comment-text" },
                                    React.createElement("span", { className: "username" },
                                        "Maria Gonzales",
                                        React.createElement("span", { className: "text-muted pull-right" }, "8:03 PM Today")),
                                    "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.")),
                            React.createElement("div", { className: "box-comment" },
                                React.createElement("img", { className: "img-circle img-sm", src: "assets/dist/img/user4-128x128.jpg", alt: "User Image" }),
                                React.createElement("div", { className: "comment-text" },
                                    React.createElement("span", { className: "username" },
                                        "Luna Stark",
                                        React.createElement("span", { className: "text-muted pull-right" }, "8:03 PM Today")),
                                    "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout."))),
                        React.createElement("div", { className: "box-footer" },
                            React.createElement("form", { action: "#", method: "post" },
                                React.createElement("img", { className: "img-responsive img-circle img-sm", src: "assets/dist/img/user4-128x128.jpg", alt: "Alt Text" }),
                                React.createElement("div", { className: "img-push" },
                                    React.createElement("input", { type: "text", className: "form-control input-sm", placeholder: "Press enter to post comment" })))))),
                React.createElement("div", { className: "col-md-6" },
                    React.createElement("div", { className: "box box-widget" },
                        React.createElement("div", { className: "box-header with-border" },
                            React.createElement("div", { className: "user-block" },
                                React.createElement("img", { className: "img-circle", src: "assets/dist/img/user1-128x128.jpg", alt: "User Image" }),
                                React.createElement("span", { className: "username" },
                                    React.createElement("a", { href: "#" }, "Jonathan Burke Jr.")),
                                React.createElement("span", { className: "description" }, "Shared publicly - 7:30 PM Today")),
                            React.createElement("div", { className: "box-tools" },
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-toggle": "tooltip", title: "Mark as read" },
                                    React.createElement("i", { className: "fa fa-circle-o" })),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "collapse" },
                                    React.createElement("i", { className: "fa fa-minus" })),
                                React.createElement("button", { type: "button", className: "btn btn-box-tool", "data-widget": "remove" },
                                    React.createElement("i", { className: "fa fa-times" })))),
                        React.createElement("div", { className: "box-body" },
                            React.createElement("p", null, "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at"),
                            React.createElement("p", null, "the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth."),
                            React.createElement("div", { className: "attachment-block clearfix" },
                                React.createElement("img", { className: "attachment-img", src: "assets/dist/img/photo1.png", alt: "Attachment Image" }),
                                React.createElement("div", { className: "attachment-pushed" },
                                    React.createElement("h4", { className: "attachment-heading" },
                                        React.createElement("a", { href: "http://www.lipsum.com/" }, "Lorem ipsum text generator")),
                                    React.createElement("div", { className: "attachment-text" },
                                        "Description about the attachment can be placed here. Lorem Ipsum is simply dummy text of the printing and typesetting industry... ",
                                        React.createElement("a", { href: "#" }, "more")))),
                            React.createElement("button", { type: "button", className: "btn btn-default btn-xs" },
                                React.createElement("i", { className: "fa fa-share" }),
                                " Share"),
                            React.createElement("button", { type: "button", className: "btn btn-default btn-xs" },
                                React.createElement("i", { className: "fa fa-thumbs-o-up" }),
                                " Like"),
                            React.createElement("span", { className: "pull-right text-muted" }, "45 likes - 2 comments")),
                        React.createElement("div", { className: "box-footer box-comments" },
                            React.createElement("div", { className: "box-comment" },
                                React.createElement("img", { className: "img-circle img-sm", src: "assets/dist/img/user3-128x128.jpg", alt: "User Image" }),
                                React.createElement("div", { className: "comment-text" },
                                    React.createElement("span", { className: "username" },
                                        "Maria Gonzales",
                                        React.createElement("span", { className: "text-muted pull-right" }, "8:03 PM Today")),
                                    "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.")),
                            React.createElement("div", { className: "box-comment" },
                                React.createElement("img", { className: "img-circle img-sm", src: "assets/dist/img/user5-128x128.jpg", alt: "User Image" }),
                                React.createElement("div", { className: "comment-text" },
                                    React.createElement("span", { className: "username" },
                                        "Nora Havisham",
                                        React.createElement("span", { className: "text-muted pull-right" }, "8:03 PM Today")),
                                    "The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English."))),
                        React.createElement("div", { className: "box-footer" },
                            React.createElement("form", { action: "#", method: "post" },
                                React.createElement("img", { className: "img-responsive img-circle img-sm", src: "assets/dist/img/user4-128x128.jpg", alt: "Alt Text" }),
                                React.createElement("div", { className: "img-push" },
                                    React.createElement("input", { type: "text", className: "form-control input-sm", placeholder: "Press enter to post comment" }))))))))));
};
exports.default = Widgets;
//# sourceMappingURL=Widgets.js.map